version: '3.7'

services:
  scala-build:
    container_name: scala-build
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/qa/code
    volumes:
      - ".:/home/qa/code"
    entrypoint: ["sh", "-c", "sleep infinity"]
    environment:
      - TZ=Asia/Tokyo
      - LC_ALL=en_US.UTF-8

  scala:
    container_name: scala
    image: lecaoquochung/scala:test
    working_dir: /home/qa/code
    volumes:
      - ".:/home/qa/code"
    entrypoint: ["sh", "-c", "sbt run"]
    # command: >
    #   sh -c "python3 robotframework/login/server.py" 
    environment:
      - TZ=Asia/Tokyo
      - LC_ALL=en_US.UTF-8
    ports:
      - 39000:9000
      
  python:
    container_name: python
    image: lecaoquochung/scala:test
    working_dir: /home/qa/code
    volumes:
      - ".:/home/qa/code"
    command: >
      sh -c "python3 robotframework/login/server.py"
    environment:
      - TZ=Asia/Tokyo
      - LC_ALL=en_US.UTF-8
    ports:
      - 39001:9001