version: '3.3'

services:
  scala-build:
    container_name: scala-build
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/qa/code
    volumes:
      - ".:/home/qa/code"
    entrypoint: ["sh", "-c", "sleep infinity"]
    environment:
      - TZ=Asia/Tokyo
      - LC_ALL=en_US.UTF-8
    # ports:
      # - 9001:80
      # - 9002:9000

  scala:
    container_name: scala
    image: lecaoquochung/scala:dev
    working_dir: /home/qa/code
    volumes:
      - "$PWD.circleci/start-server.sh:/docker-entrypoint-initdb.d/start-server.sh"
      - ".:/home/qa/code"
    # entrypoint: [ "sh", "-c", "sleep infinity" ]
    # entrypoint: [ "sh", "-c", "sbt run" ]
    # https://stackoverflow.com/questions/30063907/using-docker-compose-how-to-execute-multiple-commands
    command: >
      sh -c "sbt run"
    environment:
      - TZ=Asia/Tokyo
      - LC_ALL=en_US.UTF-8
    ports:
      - 39000:9000
      - 39001:9001